credentials:
  system:
    domainCredentials:
    - credentials:
      - fileSystemServiceAccountCredential:
          id: "f047a4ab-a375-4bad-a0dd-ec4e5bdd5147"
          scope: GLOBAL
      - usernamePassword:
          description: "gitlab凭证2"
          id: "gitlab-login"
          password: "{AQAAABAAAAAg2e84MUeYVb9rGPbBjHT/ngZNRSrScb14vhnm01B61Uv/187jLbPdJG5eYDPCJCHH}"
          scope: GLOBAL
          username: "jenkins"
      - usernamePassword:
          description: "镜像仓库帐号1"
          id: "docker-registry-account"
          password: "{AQAAABAAAAAQ+0yzIFrWX1+NjhHA07noJVzZqbSzZPQA5UXCWqNJTUc=}"
          scope: GLOBAL
          username: "gaoshan@tmatrix"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
  - kubernetes:
      containerCap: 10
      containerCapStr: "10"
      jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
      jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
      name: "kubernetes"
      namespace: "jenkins"
      podLabels:
      - key: "jenkins/jenkins-jenkins-agent"
        value: "true"
      serverUrl: "https://kubernetes.default"
      templates:
      - containers:
        - args: "^${computer.jnlpmac} ^${computer.name}"
          envVars:
          - envVar:
              key: "JENKINS_URL"
              value: "http://jenkins.jenkins.svc.cluster.local:8080/"
          image: "jenkins/inbound-agent:4.6-1"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          resourceLimitCpu: "512m"
          resourceLimitMemory: "512Mi"
          resourceRequestCpu: "512m"
          resourceRequestMemory: "512Mi"
          workingDir: "/home/jenkins/agent"
        - args: "99d"
          command: "sleep"
          image: "bitnami/kubectl:1.20"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "kubectl"
          workingDir: "/home/jenkins/agent"
        id: "1fb04a2518b4d552cc48c211c7558f31b004aa0bcbaf256922b415df4b70cb82"
        label: "jenkins-jenkins-agent"
        name: "default"
        nodeUsageMode: "NORMAL"
        podRetention: "never"
        runAsGroup: "0"
        runAsUser: "0"
        serviceAccount: "default"
        slaveConnectTimeout: 100
        slaveConnectTimeoutStr: "100"
        volumes:
        - hostPathVolume:
            hostPath: "/etc/docker"
            mountPath: "/etc/docker"
        - hostPathVolume:
            hostPath: "/usr/bin/docker"
            mountPath: "/usr/bin/docker"
        - hostPathVolume:
            hostPath: "/var/run/docker.sock"
            mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "merge"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "hudson.diagnosis.ReverseProxySetupMonitor"
  labelAtoms:
  - name: "jenkins-jenkins-agent"
  - name: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "Jenkins Admin"
        properties:
        - "apiToken"
        - "mailer"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
    - simpleBuildDiscarder:
        discarder:
          logRotator:
            numToKeepStr: "5"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://jenkins:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
